name: ci
on:
  workflow_run:
    workflows: ["Change Log Generator"] 
    types: [completed]
permissions:
  contents: write
jobs:
  deploy-docs:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.pull_requests | length) > 0 &&
      startsWith(
        github.event.workflow_run.pull_requests[0].head.ref,
        'chore/changelog-'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # pull_requests[0].head.sha = PR ブランチの最新コミット
          ref: ${{ github.event.workflow_run.pull_requests[0].head.sha }}
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: | 
          pip install tox
          tox -e docs